
from pathlib import Path
import subprocess, sys

# Re-run the complete Phase 8 build from the repository root.
# This package was generated by /mnt/data/build_phase8.py.
print('Phase 8 package is already built. To rebuild, run: python /mnt/data/build_phase8.py')
